"""Promenjene veze vol 2

Revision ID: 3bdd4888eb6f
Revises: e260f86ee478
Create Date: 2023-03-14 18:16:24.286054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bdd4888eb6f'
down_revision = 'e260f86ee478'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
