"""Promenio ime tabele termina

Revision ID: 42755ec340b0
Revises: 4ad49127d726
Create Date: 2023-03-01 17:00:39.407792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42755ec340b0'
down_revision = '4ad49127d726'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zauzeti_termini',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frizer_id', sa.Integer(), nullable=True),
    sa.Column('datum', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['frizer_id'], ['frizeri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zauzeti_termini_id'), 'zauzeti_termini', ['id'], unique=False)
    op.drop_index('ix_zauzeti termini_id', table_name='zauzeti termini')
    op.drop_table('zauzeti termini')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zauzeti termini',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('frizer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('datum', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['frizer_id'], ['frizeri.id'], name='zauzeti termini_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_zauzeti termini_id', 'zauzeti termini', ['id'], unique=False)
    op.drop_index(op.f('ix_zauzeti_termini_id'), table_name='zauzeti_termini')
    op.drop_table('zauzeti_termini')
    # ### end Alembic commands ###
