"""Added user table

Revision ID: 4ad49127d726
Revises: 
Create Date: 2023-03-01 16:31:50.682343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad49127d726'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frizeri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('pocetak_radnog_vremena', sa.DateTime(), nullable=True),
    sa.Column('kraj_radnog_vremena', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frizeri_id'), 'frizeri', ['id'], unique=False)
    op.create_index(op.f('ix_frizeri_name'), 'frizeri', ['name'], unique=False)
    op.create_table('zauzeti termini',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frizer_id', sa.Integer(), nullable=True),
    sa.Column('datum', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['frizer_id'], ['frizeri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zauzeti termini_id'), 'zauzeti termini', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zauzeti termini_id'), table_name='zauzeti termini')
    op.drop_table('zauzeti termini')
    op.drop_index(op.f('ix_frizeri_name'), table_name='frizeri')
    op.drop_index(op.f('ix_frizeri_id'), table_name='frizeri')
    op.drop_table('frizeri')
    # ### end Alembic commands ###
