"""Promenio vezu

Revision ID: e260f86ee478
Revises: 42755ec340b0
Create Date: 2023-03-01 17:05:23.563690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e260f86ee478'
down_revision = '42755ec340b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
